os:
- linux
language: ruby
rvm:
- jruby
sudo: required
dist: trusty
install:
- bundle install
script:
- bundle exec rake war
deploy:
  provider: releases
  api_key:
    secure: GeYGzycBHlIPWAcG+xt90fs/hqWxYVkpodm1aEL6Wkk4M6TXC7CQPtjOaBR2jQ/joIJ7xKYnYfcIqk1mg/97hnJTsDWQBG2PyFpCRrZVGRf85LZ1EQ4PVfkQFgcnYxhHmknJbQ1OWOMg4ylHsAl31lmTN2wmAyBrIizpBdlTilY=
  file: activeadmin-demo.war
  on:
    repo: getgauge-examples/activeadmin-demo
