os:
  - linux
language: ruby
rvm:
  - jruby
sudo: required
dist: trusty
install:
  - bundle install --path vendor/bundle
script:
  - RACK_ENV=production bundle exec rake war
  - nohup java -jar activeadmin-demo.war >/dev/null 2>&1 &
  - sleep 30
  - [[ `curl -o /dev/null --silent --head --write-out '%{http_code}\n' http://localhost:8080` == 200 ]] && echo "HTTP OK" || echo "HTTP failed" && exit -1
before_deploy:
  - export RELEASE_WAR_FILE=$(ls activeadmin-demo.war)
  - echo "deploying $RELEASE_WAR_FILE to GitHub releases"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: GeYGzycBHlIPWAcG+xt90fs/hqWxYVkpodm1aEL6Wkk4M6TXC7CQPtjOaBR2jQ/joIJ7xKYnYfcIqk1mg/97hnJTsDWQBG2PyFpCRrZVGRf85LZ1EQ4PVfkQFgcnYxhHmknJbQ1OWOMg4ylHsAl31lmTN2wmAyBrIizpBdlTilY=
  file: "${RELEASE_WAR_FILE}"
  on:
    repo: getgauge-examples/activeadmin-demo
